//---------------------------------------------------------------------------

#ifndef Unit1H
#define Unit1H
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <ExtCtrls.hpp>
//---------------------------------------------------------------------------
class TForm1 : public TForm
{
__published:	// IDE-managed Components
        TImage *Image1;
        TImage *Image2;
        TImage *Image3;
        TImage *Image4;
        TImage *Image5;
        TImage *Image6;
        TImage *Image7;
        TImage *Image8;
        TImage *Image9;
        TImage *Image10;
        TImage *Image11;
        TImage *Image12;
        TImage *Image13;
        TImage *Image14;
        TImage *Image15;
        TImage *Image16;
        TImage *Image17;
        TImage *Image18;
        TImage *Image19;
        TImage *Image20;
        TImage *Image21;
        TImage *Image22;
        TImage *Image23;
        TImage *Image24;
        TImage *Image25;
        TImage *Image26;
        TImage *Image27;
        TImage *Image28;
        TImage *Image29;
        TImage *Image30;
        TImage *Image31;
        TImage *Image32;
        TImage *Image33;
        TImage *Image34;
        TImage *Image35;
        TImage *Image36;
        TImage *Image37;
        TImage *Image38;
        TImage *Image39;
        TImage *Image40;
        TImage *Image41;
        TImage *Image42;
        TImage *Image43;
        TImage *Image44;
        TImage *Image45;
        TImage *Image46;
        TImage *Image47;
        TImage *Image48;
        TImage *Image49;
        TImage *Image50;
        TImage *Image51;
        TImage *Image52;
        TImage *Image53;
        TImage *Image54;
        TImage *Image55;
        TImage *Image56;
        TImage *Image57;
        TImage *Image58;
        TImage *Image59;
        TImage *Image60;
        TImage *Image61;
        TImage *Image62;
        TImage *Image63;
        TImage *Image64;
        TImage *Image65;
        TImage *Image66;
        TImage *Image67;
        TImage *Image68;
        TImage *Image69;
        TImage *Image70;
        TImage *Image71;
        TImage *Image72;
        TImage *Image73;
        TImage *Image74;
        TImage *Image75;
        TImage *Image76;
        TImage *Image77;
        TImage *Image78;
        TImage *Image79;
        TImage *Image80;
        TImage *Image81;
        TImage *Image82;
        TImage *Image83;
        TImage *Image84;
        TImage *Image85;
        TImage *Image86;
        TImage *Image87;
        TImage *Image88;
        TImage *Image89;
        TImage *Image90;
        TImage *Image91;
        TImage *Image92;
        TImage *Image93;
        TImage *Image94;
        TImage *Image95;
        TImage *Image96;
        TImage *Image97;
        TImage *Image98;
        TImage *Image99;
        TImage *Image100;
        TImage *Image101;
        TImage *Image102;
        TImage *Image103;
        TImage *Image104;
        TImage *Image105;
        TImage *Image106;
        TImage *Image107;
        TImage *Image108;
        TImage *Image109;
        TImage *Image110;
        TImage *Image111;
        TImage *Image112;
        TImage *Image113;
        TImage *Image114;
        TImage *Image115;
        TImage *Image116;
        TImage *Image117;
        TImage *Image118;
        TImage *Image119;
        TImage *Image120;
        TImage *Image121;
        TImage *Image122;
        TImage *Image123;
        TImage *Image124;
        TImage *Image125;
        TImage *Image126;
        TImage *Image127;
        TImage *Image128;
        TImage *Image129;
        TImage *Image130;
        TImage *Image131;
        TImage *Image132;
        TImage *Image133;
        TImage *Image134;
        TImage *Image135;
        TImage *Image136;
        TImage *Image137;
        TImage *Image138;
        TImage *Image139;
        TImage *Image140;
        TImage *Image141;
        TImage *Image142;
        TImage *Image143;
        TImage *Image144;
        TImage *Image145;
        TImage *Image146;
        TImage *Image147;
        TImage *Image148;
        TImage *Image149;
        TImage *Image150;
        TImage *Image151;
        TImage *Image152;
        TImage *Image153;
        TImage *Image154;
        TImage *Image155;
        TImage *Image156;
        TImage *Image157;
        TImage *Image158;
        TImage *Image159;
        TImage *Image160;
        TImage *Image161;
        TImage *Image162;
        TImage *Image163;
        TImage *Image164;
        TImage *Image165;
        TImage *Image166;
        TImage *Image167;
        TImage *Image168;
        TImage *Image169;
        TImage *Image170;
        TImage *Image171;
        TImage *Image172;
        TImage *Image173;
        TImage *Image174;
        TImage *Image175;
        TImage *Image176;
        TImage *Image177;
        TImage *Image178;
        TImage *Image179;
        TImage *Image180;
        TImage *Image181;
        TImage *Image182;
        TImage *Image183;
        TImage *Image184;
        TImage *Image185;
        TImage *Image186;
        TImage *Image187;
        TImage *Image188;
        TImage *Image189;
        TImage *Image190;
        TImage *Image191;
        TImage *Image192;
        TImage *Image193;
        TImage *Image194;
        TImage *Image195;
        TImage *Image196;
        TImage *Image197;
        TImage *Image198;
        TImage *Image199;
        TImage *Image200;
        TImage *Image201;
        TImage *Image202;
        TImage *Image203;
        TImage *Image204;
        TImage *Image205;
        TImage *Image206;
        TImage *Image207;
        TImage *Image208;
        TImage *Image209;
        TImage *Image210;
        TImage *Image211;
        TImage *Image212;
        TImage *Image213;
        TImage *Image214;
        TImage *Image215;
        TImage *Image216;
        TImage *Image217;
        TImage *Image218;
        TImage *Image219;
        TImage *Image220;
        TImage *Image221;
        TImage *Image222;
        TImage *Image223;
        TImage *Image224;
        TImage *Image225;
        void __fastcall Image1Click(TObject *Sender);
        void __fastcall Image2Click(TObject *Sender);
        void __fastcall Image3Click(TObject *Sender);
        void __fastcall Image4Click(TObject *Sender);
        void __fastcall Image5Click(TObject *Sender);
        void __fastcall Image6Click(TObject *Sender);
        void __fastcall Image7Click(TObject *Sender);
        void __fastcall Image8Click(TObject *Sender);
        void __fastcall Image9Click(TObject *Sender);
        void __fastcall Image10Click(TObject *Sender);
        void __fastcall Image12Click(TObject *Sender);
        void __fastcall Image11Click(TObject *Sender);
        void __fastcall Image13Click(TObject *Sender);
        void __fastcall Image14Click(TObject *Sender);
        void __fastcall Image15Click(TObject *Sender);
        void __fastcall Image16Click(TObject *Sender);
        void __fastcall Image17Click(TObject *Sender);
        void __fastcall Image18Click(TObject *Sender);
        void __fastcall Image19Click(TObject *Sender);
        void __fastcall Image20Click(TObject *Sender);
        void __fastcall Image21Click(TObject *Sender);
        void __fastcall Image22Click(TObject *Sender);
        void __fastcall Image23Click(TObject *Sender);
        void __fastcall Image24Click(TObject *Sender);
        void __fastcall Image25Click(TObject *Sender);
        void __fastcall Image26Click(TObject *Sender);
        void __fastcall Image27Click(TObject *Sender);
        void __fastcall Image28Click(TObject *Sender);
        void __fastcall Image29Click(TObject *Sender);
        void __fastcall Image30Click(TObject *Sender);
        void __fastcall Image31Click(TObject *Sender);
        void __fastcall Image32Click(TObject *Sender);
        void __fastcall Image33Click(TObject *Sender);
        void __fastcall Image34Click(TObject *Sender);
        void __fastcall Image35Click(TObject *Sender);
        void __fastcall Image36Click(TObject *Sender);
        void __fastcall Image37Click(TObject *Sender);
        void __fastcall Image38Click(TObject *Sender);
        void __fastcall Image39Click(TObject *Sender);
        void __fastcall Image40Click(TObject *Sender);
        void __fastcall Image41Click(TObject *Sender);
        void __fastcall Image42Click(TObject *Sender);
        void __fastcall Image43Click(TObject *Sender);
        void __fastcall Image44Click(TObject *Sender);
        void __fastcall Image45Click(TObject *Sender);
        void __fastcall Image46Click(TObject *Sender);
        void __fastcall Image47Click(TObject *Sender);
        void __fastcall Image48Click(TObject *Sender);
        void __fastcall Image49Click(TObject *Sender);
        void __fastcall Image50Click(TObject *Sender);
        void __fastcall Image51Click(TObject *Sender);
        void __fastcall Image52Click(TObject *Sender);
        void __fastcall Image53Click(TObject *Sender);
        void __fastcall Image54Click(TObject *Sender);
        void __fastcall Image55Click(TObject *Sender);
        void __fastcall Image56Click(TObject *Sender);
        void __fastcall Image57Click(TObject *Sender);
        void __fastcall Image58Click(TObject *Sender);
        void __fastcall Image59Click(TObject *Sender);
        void __fastcall Image60Click(TObject *Sender);
        void __fastcall Image61Click(TObject *Sender);
        void __fastcall Image62Click(TObject *Sender);
        void __fastcall Image63Click(TObject *Sender);
        void __fastcall Image64Click(TObject *Sender);
        void __fastcall Image65Click(TObject *Sender);
        void __fastcall Image66Click(TObject *Sender);
        void __fastcall Image67Click(TObject *Sender);
        void __fastcall Image68Click(TObject *Sender);
        void __fastcall Image69Click(TObject *Sender);
        void __fastcall Image70Click(TObject *Sender);
        void __fastcall Image71Click(TObject *Sender);
        void __fastcall Image72Click(TObject *Sender);
        void __fastcall Image73Click(TObject *Sender);
        void __fastcall Image74Click(TObject *Sender);
        void __fastcall Image75Click(TObject *Sender);
        void __fastcall Image76Click(TObject *Sender);
        void __fastcall Image77Click(TObject *Sender);
        void __fastcall Image78Click(TObject *Sender);
        void __fastcall Image79Click(TObject *Sender);
        void __fastcall Image80Click(TObject *Sender);
        void __fastcall Image81Click(TObject *Sender);
        void __fastcall Image82Click(TObject *Sender);
        void __fastcall Image83Click(TObject *Sender);
        void __fastcall Image84Click(TObject *Sender);
        void __fastcall Image85Click(TObject *Sender);
        void __fastcall Image86Click(TObject *Sender);
        void __fastcall Image87Click(TObject *Sender);
        void __fastcall Image88Click(TObject *Sender);
        void __fastcall Image89Click(TObject *Sender);
        void __fastcall Image90Click(TObject *Sender);
        void __fastcall Image91Click(TObject *Sender);
        void __fastcall Image92Click(TObject *Sender);
        void __fastcall Image93Click(TObject *Sender);
        void __fastcall Image94Click(TObject *Sender);
        void __fastcall Image95Click(TObject *Sender);
        void __fastcall Image96Click(TObject *Sender);
        void __fastcall Image97Click(TObject *Sender);
        void __fastcall Image98Click(TObject *Sender);
        void __fastcall Image99Click(TObject *Sender);
        void __fastcall Image100Click(TObject *Sender);
        void __fastcall Image101Click(TObject *Sender);
        void __fastcall Image102Click(TObject *Sender);
        void __fastcall Image103Click(TObject *Sender);
        void __fastcall Image104Click(TObject *Sender);
        void __fastcall Image105Click(TObject *Sender);
        void __fastcall Image106Click(TObject *Sender);
        void __fastcall Image107Click(TObject *Sender);
        void __fastcall Image108Click(TObject *Sender);
        void __fastcall Image109Click(TObject *Sender);
        void __fastcall Image110Click(TObject *Sender);
        void __fastcall Image111Click(TObject *Sender);
        void __fastcall Image112Click(TObject *Sender);
        void __fastcall Image113Click(TObject *Sender);
        void __fastcall Image114Click(TObject *Sender);
        void __fastcall Image115Click(TObject *Sender);
        void __fastcall Image116Click(TObject *Sender);
        void __fastcall Image117Click(TObject *Sender);
        void __fastcall Image118Click(TObject *Sender);
        void __fastcall Image119Click(TObject *Sender);
        void __fastcall Image120Click(TObject *Sender);
        void __fastcall Image121Click(TObject *Sender);
        void __fastcall Image122Click(TObject *Sender);
        void __fastcall Image123Click(TObject *Sender);
        void __fastcall Image124Click(TObject *Sender);
        void __fastcall Image125Click(TObject *Sender);
        void __fastcall Image126Click(TObject *Sender);
        void __fastcall Image127Click(TObject *Sender);
        void __fastcall Image128Click(TObject *Sender);
        void __fastcall Image129Click(TObject *Sender);
        void __fastcall Image130Click(TObject *Sender);
        void __fastcall Image131Click(TObject *Sender);
        void __fastcall Image132Click(TObject *Sender);
        void __fastcall Image133Click(TObject *Sender);
        void __fastcall Image134Click(TObject *Sender);
        void __fastcall Image135Click(TObject *Sender);
        void __fastcall Image136Click(TObject *Sender);
        void __fastcall Image137Click(TObject *Sender);
        void __fastcall Image138Click(TObject *Sender);
        void __fastcall Image139Click(TObject *Sender);
        void __fastcall Image140Click(TObject *Sender);
        void __fastcall Image141Click(TObject *Sender);
        void __fastcall Image142Click(TObject *Sender);
        void __fastcall Image143Click(TObject *Sender);
        void __fastcall Image144Click(TObject *Sender);
        void __fastcall Image145Click(TObject *Sender);
        void __fastcall Image146Click(TObject *Sender);
        void __fastcall Image147Click(TObject *Sender);
        void __fastcall Image148Click(TObject *Sender);
        void __fastcall Image149Click(TObject *Sender);
        void __fastcall Image150Click(TObject *Sender);
        void __fastcall Image151Click(TObject *Sender);
        void __fastcall Image152Click(TObject *Sender);
        void __fastcall Image153Click(TObject *Sender);
        void __fastcall Image154Click(TObject *Sender);
        void __fastcall Image155Click(TObject *Sender);
        void __fastcall Image156Click(TObject *Sender);
        void __fastcall Image157Click(TObject *Sender);
        void __fastcall Image158Click(TObject *Sender);
        void __fastcall Image159Click(TObject *Sender);
        void __fastcall Image160Click(TObject *Sender);
        void __fastcall Image161Click(TObject *Sender);
        void __fastcall Image162Click(TObject *Sender);
        void __fastcall Image163Click(TObject *Sender);
        void __fastcall Image164Click(TObject *Sender);
        void __fastcall Image165Click(TObject *Sender);
        void __fastcall Image166Click(TObject *Sender);
        void __fastcall Image167Click(TObject *Sender);
        void __fastcall Image168Click(TObject *Sender);
        void __fastcall Image169Click(TObject *Sender);
        void __fastcall Image170Click(TObject *Sender);
        void __fastcall Image171Click(TObject *Sender);
        void __fastcall Image172Click(TObject *Sender);
        void __fastcall Image173Click(TObject *Sender);
        void __fastcall Image174Click(TObject *Sender);
        void __fastcall Image175Click(TObject *Sender);
        void __fastcall Image176Click(TObject *Sender);
        void __fastcall Image177Click(TObject *Sender);
        void __fastcall Image178Click(TObject *Sender);
        void __fastcall Image179Click(TObject *Sender);
        void __fastcall Image180Click(TObject *Sender);
        void __fastcall Image181Click(TObject *Sender);
        void __fastcall Image182Click(TObject *Sender);
        void __fastcall Image183Click(TObject *Sender);
        void __fastcall Image184Click(TObject *Sender);
        void __fastcall Image185Click(TObject *Sender);
        void __fastcall Image186Click(TObject *Sender);
        void __fastcall Image187Click(TObject *Sender);
        void __fastcall Image188Click(TObject *Sender);
        void __fastcall Image189Click(TObject *Sender);
        void __fastcall Image190Click(TObject *Sender);
        void __fastcall Image191Click(TObject *Sender);
        void __fastcall Image192Click(TObject *Sender);
        void __fastcall Image193Click(TObject *Sender);
        void __fastcall Image194Click(TObject *Sender);
        void __fastcall Image195Click(TObject *Sender);
        void __fastcall Image196Click(TObject *Sender);
        void __fastcall Image197Click(TObject *Sender);
        void __fastcall Image198Click(TObject *Sender);
        void __fastcall Image199Click(TObject *Sender);
        void __fastcall Image200Click(TObject *Sender);
        void __fastcall Image201Click(TObject *Sender);
        void __fastcall Image202Click(TObject *Sender);
        void __fastcall Image203Click(TObject *Sender);
        void __fastcall Image204Click(TObject *Sender);
        void __fastcall Image205Click(TObject *Sender);
        void __fastcall Image206Click(TObject *Sender);
        void __fastcall Image207Click(TObject *Sender);
        void __fastcall Image208Click(TObject *Sender);
        void __fastcall Image209Click(TObject *Sender);
        void __fastcall Image210Click(TObject *Sender);
        void __fastcall Image211Click(TObject *Sender);
        void __fastcall Image212Click(TObject *Sender);
        void __fastcall Image213Click(TObject *Sender);
        void __fastcall Image214Click(TObject *Sender);
        void __fastcall Image215Click(TObject *Sender);
        void __fastcall Image216Click(TObject *Sender);
        void __fastcall Image217Click(TObject *Sender);
        void __fastcall Image218Click(TObject *Sender);
        void __fastcall Image219Click(TObject *Sender);
        void __fastcall Image220Click(TObject *Sender);
        void __fastcall Image221Click(TObject *Sender);
        void __fastcall Image222Click(TObject *Sender);
        void __fastcall Image223Click(TObject *Sender);
        void __fastcall Image224Click(TObject *Sender);
        void __fastcall Image225Click(TObject *Sender);
private:	// User declarations
public:		// User declarations
        __fastcall TForm1(TComponent* Owner);
};
//---------------------------------------------------------------------------
extern PACKAGE TForm1 *Form1;
//---------------------------------------------------------------------------
#endif
 